# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3523a7b7ab757c7a488ce5ead2bbb60d70abe95e6d0eda02a0088d37776ed72cfea33e691f4e1f7501b285cd91e62d49c8572f826f00deba323d9c155f137998

test:
  secret_key_base: 5a3170cf84818c2590f2cdf0befdac1a5299aff79ac3ae31ad7f9e91e899e5517c1a073e7c4780a7761cb6bded125691ab64811eafe251548ed4d27601c80e6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
