--- !ditz.rubyforge.org,2008-03-06/project 
name: rails-mathpad
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: rails-mathpad
- !ditz.rubyforge.org,2008-03-06/component 
  name: Model
- !ditz.rubyforge.org,2008-03-06/component 
  name: WebUI
- !ditz.rubyforge.org,2008-03-06/component 
  name: Users
- !ditz.rubyforge.org,2008-03-06/component 
  name: Social
- !ditz.rubyforge.org,2008-03-06/component 
  name: Compatibility
- !ditz.rubyforge.org,2008-03-06/component 
  name: Userless
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.0.0.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2015-06-10 20:45:07.048512 Z
    - Matias Eyzaguirre <matias@fortlogic.net>
    - created
    - First major release. Everything up til this point should be considered incomplete.
css: style.css
