require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ScratchpadsController, type: :controller do

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScratchpadsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all scratchpads as @scratchpads" do
      scratchpad = Fabricate(:scratchpad)
      get :index, {}, valid_session
      expect(assigns(:scratchpads)).to eq([scratchpad])
    end
  end

  describe "GET #show" do
    it "assigns the requested scratchpad as @scratchpad" do
      scratchpad = Fabricate(:scratchpad)
      get :show, {:id => scratchpad.to_param}, valid_session
      expect(assigns(:scratchpad)).to eq(scratchpad)
    end
  end

  describe "GET #new" do
    it "assigns a new scratchpad as @scratchpad" do
      get :new, {}, valid_session
      expect(assigns(:scratchpad)).to be_a_new(Scratchpad)
    end
  end

  describe "GET #edit" do
    it "assigns the requested scratchpad as @scratchpad" do
      scratchpad = Fabricate(:scratchpad)
      get :edit, {:id => scratchpad.to_param}, valid_session
      expect(assigns(:scratchpad)).to eq(scratchpad)
    end
  end

  describe "POST #create" do
    context "with valid params" do

      before(:each) do
        user = Fabricate(:user)
        @scratchpad_attributes = Fabricate.attributes_for(:scratchpad).merge({"user_id" => user.id})
      end

      it "creates a new Scratchpad" do
        expect {
          post :create, {:scratchpad => @scratchpad_attributes}, valid_session
        }.to change(Scratchpad, :count).by(1)
      end

      it "assigns a newly created scratchpad as @scratchpad" do
        post :create, {:scratchpad => @scratchpad_attributes}, valid_session
        expect(assigns(:scratchpad)).to be_a(Scratchpad)
        expect(assigns(:scratchpad)).to be_persisted
      end

      it "redirects to the created scratchpad" do
        # TODO: This will require the user to be logged in to work,
        # the user_id will be that of the current user.
        post :create, {:scratchpad => @scratchpad_attributes}, valid_session
        expect(response).to redirect_to(Scratchpad.last)
      end

      it "should fail if user_id is not that of the current user" do
        expect(1).to equal(2)
      end
    end

    context "with invalid params" do
      before(:each) do
        @wrong_attributes = lambda {
          {
            "title" => nil,
            "lcars_interface_id" => 47
          }
        }
      end
      
      it "assigns a newly created but unsaved scratchpad as @scratchpad" do
        post :create, {:scratchpad => @wrong_attributes.call()}, valid_session
        expect(assigns(:scratchpad)).to be_a_new(Scratchpad)
      end

      it "re-renders the 'new' template" do
        post :create, {:scratchpad => @wrong_attributes.call()}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        Fabricate.attributes_for(:scratchpad)
      }

      it "updates the requested scratchpad" do
        scratchpad = Fabricate(:scratchpad)
        put :update, {:id => scratchpad.to_param, :scratchpad => new_attributes}, valid_session
        scratchpad.reload

        expect(scratchpad.title).to eq(new_attributes.delete("title"))
        expect(scratchpad.description).to eq(new_attributes.delete("description"))
        expect(scratchpad.user.id).to eq(new_attributes.delete("user_id"))
        expect(new_attributes.count).to eq(0) # check we've tested everything
      end

      it "assigns the requested scratchpad as @scratchpad" do
        scratchpad = Fabricate(:scratchpad)
        put :update, {:id => scratchpad.to_param, :scratchpad => Fabricate.attributes_for(:scratchpad) }, valid_session
        expect(assigns(:scratchpad)).to eq(scratchpad)
      end

      it "redirects to the scratchpad" do
        scratchpad = Fabricate(:scratchpad)
        put :update, {:id => scratchpad.to_param, :scratchpad => Fabricate.attributes_for(:scratchpad) }, valid_session
        expect(response).to redirect_to(scratchpad)
      end
    end

    context "with invalid params" do
      before(:each) do
        @wrong_attributes = lambda {
          {
            "title" => nil,
            "lcars_interface_id" => 47
          }
        }
      end

      it "assigns the scratchpad as @scratchpad" do
        scratchpad = Fabricate(:scratchpad)
        put :update, {:id => scratchpad.to_param, :scratchpad => @wrong_attributes.call() }, valid_session
        expect(assigns(:scratchpad)).to eq(scratchpad)
      end

      it "re-renders the 'edit' template" do
        scratchpad = Fabricate(:scratchpad)
        put :update, {:id => scratchpad.to_param, :scratchpad => @wrong_attributes.call() }, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested scratchpad" do
      scratchpad = Fabricate(:scratchpad)
      expect {
        delete :destroy, {:id => scratchpad.to_param}, valid_session
      }.to change(Scratchpad, :count).by(-1)
    end

    it "redirects to the scratchpads list" do
      scratchpad = Fabricate(:scratchpad)
      delete :destroy, {:id => scratchpad.to_param}, valid_session
      expect(response).to redirect_to(scratchpads_url)
    end
  end

end
